### ISSUE TITLE
tetrad asks for toytree although it is already installed

### ISSUE THREAD

**Issue by joqb** [eaton-lab/tetrad#1]
Hi @eaton-lab,

I want to run tetrad but it keeps asking for toytree although I just installed it...
What versions do you recommend?
Thanks
```
(base) [ghanavati@bit-10 for-fastq]$ tetrad -s /filer-5/user/ghanavati/for-fastq/datatest_outfiles/datatest.snps.phy -l /filer-5/user/ghanavati/for-fastq/datatest_outfiles/datatest.snps.map -n 189chamomile -o /filer-5/user/ghanavati/for-fastq/ -c 10 -b 100 - random -q 1000000
Traceback (most recent call last):
  File "/filer-5/user/ghanavati/miniconda2/bin/tetrad", line 11, in <module>
    load_entry_point('ipyrad==0.7.30', 'console_scripts', 'tetrad')()
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/__init__.py", line 18, in <module>
    from .structure import Structure as structure
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/structure.py", line 12, in <module>
    from ipyrad.analysis.tetrad import get_spans
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/tetrad.py", line 67, in <module>
    """)
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/assemble/util.py", line 52, in __init__
    raise IPyradError(*args, **kwargs)
ipyrad.assemble.util.IPyradError:
    Error: tetrad requires the dependency 'toytree', which we haven't yet
    included in the ipyrad installation. For now, you can install toytree
    using conda with the following command:

    conda install toytree -c eaton-lab

(base) [ghanavati@bit-10 for-fastq]$ conda install toytree -c eaton-lab

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /filer-5/user/ghanavati/miniconda2

  added / updated specs:
    - toytree


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arrow-0.13.1               |           py27_0          83 KB
    custom_inherit-2.2.0       |           py27_0          30 KB  eaton-lab
    ghostscript-9.21           |                0           4 KB  eaton-lab
    multipledispatch-0.6.0     |           py27_0          21 KB
    pypng-0.0.18               |           py27_0          81 KB  eaton-lab
    reportlab-3.5.23           |   py27he686d34_0         2.2 MB
    toyplot-0.18.0             |           py27_0         342 KB  eaton-lab
    toytree-0.2.0              |           py27_1         151 KB  eaton-lab
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following NEW packages will be INSTALLED:

  arrow              pkgs/main/linux-64::arrow-0.13.1-py27_0
  custom_inherit     eaton-lab/linux-64::custom_inherit-2.2.0-py27_0
  ghostscript        eaton-lab/linux-64::ghostscript-9.21-0
  multipledispatch   pkgs/main/linux-64::multipledispatch-0.6.0-py27_0
  pypng              eaton-lab/linux-64::pypng-0.0.18-py27_0
  reportlab          pkgs/main/linux-64::reportlab-3.5.23-py27he686d34_0
  toyplot            eaton-lab/linux-64::toyplot-0.18.0-py27_0
  toytree            eaton-lab/linux-64::toytree-0.2.0-py27_1


Proceed ([y]/n)?

Downloading and Extracting Packages
pypng-0.0.18         | 81 KB     | ######################################################################## | 100%
toytree-0.2.0        | 151 KB    | ######################################################################## | 100%
ghostscript-9.21     | 4 KB      | ######################################################################## | 100%
arrow-0.13.1         | 83 KB     | ######################################################################## | 100%
custom_inherit-2.2.0 | 30 KB     | ######################################################################## | 100%
toyplot-0.18.0       | 342 KB    | ######################################################################## | 100%
multipledispatch-0.6 | 21 KB     | ######################################################################## | 100%
reportlab-3.5.23     | 2.2 MB    | ######################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) [ghanavati@bit-10 for-fastq]$ tetrad -s /filer-5/user/ghanavati/for-fastq/datatest_outfiles/datatest.snps.phy -l /filer-5/user/ghanavati/for-fastq/datatest_outfiles/datatest.snps.map -n 189chamomile -o /filer-5/user/ghanavati/for-fastq/ -c 10 -b 100 - random -q 1000000
Traceback (most recent call last):
  File "/filer-5/user/ghanavati/miniconda2/bin/tetrad", line 11, in <module>
    load_entry_point('ipyrad==0.7.30', 'console_scripts', 'tetrad')()
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/__init__.py", line 18, in <module>
    from .structure import Structure as structure
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/structure.py", line 12, in <module>
    from ipyrad.analysis.tetrad import get_spans
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/tetrad.py", line 67, in <module>
    """)
  File "/filer-5/user/ghanavati/miniconda2/lib/python2.7/site-packages/ipyrad/assemble/util.py", line 52, in __init__
    raise IPyradError(*args, **kwargs)
ipyrad.assemble.util.IPyradError:
    Error: tetrad requires the dependency 'toytree', which we haven't yet
    included in the ipyrad installation. For now, you can install toytree
    using conda with the following command:

    conda install toytree -c eaton-lab

(base) [ghanavati@bit-10 miniconda2]$ conda install toytree -c eaton-lab                                           Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

**Comment by eaton-lab** [comment]
This is now fixed, note the new conda install command: 

`conda install tetrad -c eaton-lab -c conda-forge`
