### ISSUE TITLE
Tree input appears to be a file path but does not exist

### ISSUE THREAD

**Issue by DavidRJB** [eaton-lab/tetrad#10]
Hello!

I was wondering if I can get some help with the error. I followed all the recommendations in ipyrad page and the input data its from ipyrad too.

>>> data = "/mnt/netapp1/Store_csbepgnf/seqs/tetrad/c90m131d6/c90m131d6_outs.snps.hdf5"

>>> tet = ipa.tetrad(
    name="virentes-min4",
    data=data,
    nquartets=1e6,
    nboots=16,
)

loading snps array [265 taxa x 45801 snps]
max unlinked SNPs per quartet [nloci]: 1597
quartet sampler [random]: 1000000 / 200860990

>>> tet.run(auto=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/netapp1/Store_csbepgnf/mambaforge/envs/tetrad_env/lib/python3.7/site-packages/tetrad/tetrad.py", line 527, in run
    self._get_checkpoint()
  File "/mnt/netapp1/Store_csbepgnf/mambaforge/envs/tetrad_env/lib/python3.7/site-packages/tetrad/tetrad.py", line 217, in _get_checkpoint
    self._finished_full = toytree.tree(self.trees.tree).ntips > 1
  File "/mnt/netapp1/Store_csbepgnf/mambaforge/envs/tetrad_env/lib/python3.7/site-packages/toytree/io/src/treeio.py", line 82, in tree
    internal_labels=internal_labels,
  File "/mnt/netapp1/Store_csbepgnf/mambaforge/envs/tetrad_env/lib/python3.7/site-packages/toytree/io/src/parse.py", line 116, in parse_tree
    strdata = parse_generic_to_str(data)
  File "/mnt/netapp1/Store_csbepgnf/mambaforge/envs/tetrad_env/lib/python3.7/site-packages/toytree/io/src/parse.py", line 74, in parse_generic_to_str
    "Tree input appears to be a file path "
OSError: Tree input appears to be a file path but does not exist: '/mnt/netapp1/Store_csbepgnf/seqs/tetrad/c90m131d6/analysis-tetrad/virentes-min4.tree'
>>>

I checked the analysis-tetrad and only appeared virentes-min4.input.hdf5 file. I received other error message but it was solved (AttributeError: 'str' object has no attribute 'decode')

Thanks!

**Comment by isaacovercast** [comment]
You might check the toytree version installed? There was an update to v3.0
recently which broke some things. Try rolling back to toytree 2.0.5 and let
me know how it goes.

**Comment by alexkrohn** [comment]
Confirmed that downgrading to 2.0.5 resolved this issue for me.
